config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users do
    resources :accomodations do #, except: [:show] do
      resources :photos, only: [:new, :create]
      resources :bookings, only: [:edit, :index]
    end
  end

  resources :bookings, only: [:edit, :update, :destroy]

  resources :accomodations, only: [:index, :show, :new, :update, :edit] do
    resources :bookings, only: [:new, :index, :create]
    resources :photos, only: [:new, :create]
    resources :flat_reviews, only: [:new, :create]
  end

  resources :photos, only: [:destroy] # DO NOT CHANGE THIS ROUTE

  root 'welcome#index'

end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  has_many :photos
  belongs_to :user
  # belongs_to :owner, source: :user
  has_many :bookings, dependent: :destroy
  has_many :renters, through: :bookings, source: :user
  has_many :flat_reviews, dependent: :destroy
  # belongs_to :user, class_name: "Owner", foreign_key: "owner_id"
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :description,
              presence: true
  validates :user_id,
              presence: true,
              numericality: { only_integer: true }
  validates :accomodates,
              presence: true,
              numericality: { only_integer: true }
  validates :night_rate,
              presence: true,
              numericality: { only_integer: true }
  validates :address,
              presence: true

  def self.search(query)
    #where(:locality, query) #-> This would return an exact match of the query
    where("locality like ?", "%#{query}%")
  end
end

# accomodates -> integer
# description -> text
# night_rate -> integer
# address -> string
# owner_id -> integer
# latitude -> float
# longitude -> float

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  before_action :set_user, only: [:show, :create, :destroy]
  before_action :set_accomodation, only: [:show, :edit, :update, :destroy]

  def create
    @accomodation = @user.accomodations.build(accomodations_params)
    @accomodation.save
    redirect_to user_path(@user)
  end

  def new
    @accomodation = Accomodation.new
  end

  def update
    @accomodation.update(accomodations_params)
    redirect_to @accomodation
  end

  def edit
    @accomodation = Accomodation.find(params[:id])
  end

  def index
    if params[:search]
      @accomodations = Accomodation.where(locality: params[:search]).order("night_rate ASC")
    else
      @accomodations = Accomodation.all.order("night_rate ASC")
    end
    @markers = Gmaps4rails.build_markers(@accomodations) do | accomodation, marker |
      marker.lat accomodation.latitude
      marker.lng accomodation.longitude
      marker.infowindow render_to_string(partial: "/accomodations/map_box", locals: { accomodation: accomodation })
    end
  end

  def show
    @booking = Booking.new
    @owner = @accomodation.user
    @accomodation_bookings = @accomodation.bookings
    @markers = Gmaps4rails.build_markers(@accomodation) do | accomodation, marker |
      marker.lat accomodation.latitude
      marker.lng accomodation.longitude
    end
    @new_flat_review = FlatReview.new
  end

  def destroy
    if Accomodation.find(params[:id])
      @accomodation = Accomodation.find(params[:id])
      @accomodation.destroy
      redirect_to user_path(@user)
    else
      flash[:alert] = "The accomodation that you are trying to delete has already been delete. Refresh your navigator!"
      redirect_to user_path(@user)
    end
  end

  private

  def accomodations_params
    params.require(:accomodation).permit(:accomodates, :description, :night_rate, :address, :locality, :street_number, :country, :route)
  end

  def set_user
    @user = current_user
  end

  def set_accomodation
    @accomodation = Accomodation.find(params[:id])
  end
end

# accomodates -> integer
# description -> text
# night_rate -> integer
# address -> string
# owner_id -> integer
# latitude -> float
# longitude -> float

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/views/accomodations/_map_box.html.erb
<div class="map_box">
  <h3><%= accomodation.description %></h3>
  <p><%= accomodation.address %></p>
  <%= link_to "Book me!", accomodation_path(accomodation), class: "btn btn-warning" %>
</div>

app/views/accomodations/edit.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        Edit accomodation
      </h1>
      <div id="presentation-box" class="card-block shadowed-box">
        <%= render 'shared/accomodation_form' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        Delete photos
      </h1>
      <div id="presentation-box" class="card-block shadowed-box">
         <%= render 'shared/accomodation_gallery' %>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        Upload photos
      </h1>
      <div id="presentation-box" class="card-block shadowed-box">
         <%= render 'shared/photo_form' %>
      </div>
    </div>
  </div>
</div>

app/views/accomodations/index.html.erb
<div class="container">
  <div class="row">
    <h1>List of flats around you...</h1>
    <div class="col-xs-12 col-md-6">
      <% @accomodations.each do | accomodation | %>
        <%= link_to(accomodation_path(accomodation)) do %>
          <div class="col-sm-6 col-md-6 xs-padded">
            <div class="thumbnail">
              <% if accomodation.photos.present? %>
              <%= image_tag(accomodation.photos.sample.picture.url(:medium), height: '180', width: '250') %>
              <% else %>
              <%= image_tag ("default.jpg"), height: '180', width: '250' %>
              <% end %>
              <div class="caption">
                <p><%= accomodation.description %></p>
                <p><%= "#{accomodation.locality}, #{accomodation.country}" %></p>
                <p><span class="label label-info price-label"><%= accomodation.night_rate %> €</span></p>
                <p>
                  Ratings:
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star-o"></i>
                  (19)
                </p>
                <p class="text-center">
                  <%= link_to("Book me!", accomodation_path(accomodation), class: "btn btn-default btn-sm", role: "button") %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-xs-12 col-md-6 xs-padded">
      <!-- placeholder for the map -->
      <div id="map" class="thumbnail" style="width: 100%; height: 900px;"></div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
 <%= javascript_tag do %>
   $(document).on('ready', function() {
     handler = Gmaps.build('Google');
     handler.buildMap({ internal: { id: 'map' } }, function(){
       markers = handler.addMarkers(<%= raw @markers.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
     });
   })
 <% end %>
<% end %>

app/views/accomodations/new.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        Add an accomodation
      </h1>
      <%= render 'shared/accomodation_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <br><br>
      <%= link_to "Back to Accomodation List", accomodations_path %>
    </div>
  </div>
</div>

<!--
# accomodates -> integer
# description -> text
# night_rate -> integer
# address -> string
# owner_id -> integer
# latitude -> float
# longitude -> float
-->

app/views/accomodations/show.html.erb
<div class="container">
  <div class="row">
    <p><%=  link_to "Update this accomodation", edit_user_accomodation_path(@user, @accomodation) , class: "btn btn-default btn-sm" %></p>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12">
        <% @accomodation.photos.each do |photo| %>
        <%= image_tag photo.picture.url(:medium), class:"img-thumbnail", width:"280px" %>
        <% end %>
      </div>
  </div>
</div>
<div class="container">
  <!-- TO DO: Remove <br><br> and replace with smart CSS -->
  <br><br>
  <div class="row">
      <!-- High level description -->
    <div class="col-xs-12 col-sm-offset-2 col-sm-4">
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h3>About The Owner</h3>
            <p class="text-center">
              <!-- TO DO David: Update profile picture of the owner -->
              <%= image_tag(@accomodation.user.picture.url(:medium), class: "img-circle", height: "50") %>
              <!-- TO DO: Align properly with smart CSS -->
              <br><%= "#{@owner.first_name} #{@owner.last_name}" %>
            </p>
            <p class="text-center">Ratings: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i>(1908)</p>
            <p class="text-center">
              <%= mail_to "me@domain.com", "Email-me", class: "btn btn-default" %>
            </p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h4><%= @accomodation.description %></h4>
            <p><%= "#{@accomodation.locality}, #{@accomodation.country}" %><p>
            <p>Ratings:
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star"></i>
              <i class="fa fa-star-o"></i>(19)
            </p>
            <p>Rate per night: € <%= @accomodation.night_rate %></p>
            <ul class="list-unstyled list-inline">
              <li>
                <i class="fa fa-home"></i>
                Entire home/apt
              </li>
              <li>
                <i class="fa fa-user"></i>
                <span><%= @accomodation.accomodates %></span> Guests
              </li>
              <li>
                <i class="fa fa-building"></i>
                1 Bedroom
              </li>
              <li>
                <i class="fa fa-bed"></i>
                1 Bed
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!--  Owner description -->
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h3>About The Owner</h3>
            <p class="text-center">
              <!-- TO DO David: Update profile picture of the owner -->
              <%= image_tag("beard1.jpg", class: "img-circle", height: "50") %>
              <!-- TO DO: Align properly with smart CSS -->
              <br><%= "#{@owner.first_name} #{@owner.last_name}" %>
            </p>
            <p class="text-center">Ratings: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i>(1908)</p>
            <p class="text-center">
              <%= mail_to "me@domain.com", "Email-me", class: "btn btn-default" %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- Availabilities and booking -->
    <div class="col-xs-12 col-sm-5"><!-- Availabilities -->
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h3 class="text-center">Booked Dates</h3>
            <% @accomodation_bookings.each do |booking| %>
              <div class="row">
                <div class="col-xs-8">
                  <%= "From #{booking.from.strftime("%F")} to #{booking.to.strftime("%F")} " %>
                </div>
                <div class="col-xs-4">
                  <% if booking.reviewed == false %>
                    <%= "Pending review" %>
                  <% else %>
                    <% if booking.accepted == true %>
                      <%= "Accepted" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h3 class="text-center">Book</h3>
              <%= simple_form_for [@accomodation, @booking] do |f| %>
                <%= f.input :from, as: :date, start_year: Date.today.year,
                                      end_year: Date.today.year, discard_day: false,
                                      order: [:day, :month, :year] %>
                <%= f.input :to, as: :date, start_year: Date.today.year + 1,
                                      end_year: Date.today.year, discard_day: false,
                                      order: [:day, :month, :year] %>
                <%= f.button :submit %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-9">
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <h3>About This Listing</h3>
            <p>With Hair'Bnb, you can find hairy accommodations at hairy people's places. The listing details below explain what you'll find in this space. If you have any questions, you can contact the host directly.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-offset-2 col-sm-9">
      <div class="row">
        <div class="col-xs-11">
          <div class="card-block shadowed-box">
            <div class="row">
              <h3>About This Accomodation</h3>
              <div class="col-xs-12 col-md-2">
                The Space
              </div>
              <div class="col-xs-12 col-md-4">
                <div class="row">
                  <div class="col-xs-12">
                    Bed type: Pull-out Sofa
                  </div>
                  <div class="col-xs-12">
                    Bedrooms: 1
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-2">
                Amenities
              </div>
              <div class="col-xs-12 col-md-4">
                <div class="row">
                  <div class="col-xs-12">
                    Kitchen
                  </div>
                  <div class="col-xs-12">
                    Free Parking
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-2">
                Prices
              </div>
              <div class="col-xs-12 col-md-4">
                <div class="row">
                  <div class="col-xs-12">
                    Extra people: No Charge
                  </div>
                  <div class="col-xs-12">
                    Cancellation: Moderate
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-md-2">
                Description
              </div>
              <div class="col-xs-12 col-md-8">
                Studio de 20m² refait à neuf.
                Il donne coté cour. Il se situe à 15 min de République à pied, 200m du métro ainsi que d'une station V'lille.
                Nous serons ravis de vous accueillir chez nous. Comptez sur nous pour vous donner quelques adresses en ville.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <div class="card-block shadowed-box">
        <h3>Accomodation Reviews</h3>
        <hr>
        <div class="media">
          <% @accomodation.flat_reviews.each do | review | %>
          <div class="media-left">

          </div>
          <div class="media-body">
              <h4 class="media-heading">Rating: <%= review.rating %></h4>
              <p><%= review.content %></p>
          </div>
          <hr>
          <% end %>
        </div>
        <%= simple_form_for [@accomodation, @new_flat_review] do |f| %>
          <%= f.error_notification %>
          <%= f.input :content %>
          <%= f.input :rating %>
          <%= f.button :submit, class:"btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div> <!-- row -->
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 ">
      <div class="card-block shadowed-box">
        <div id="map" style="width: 100%; height: 300px;"></div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
 <%= javascript_tag do %>
   $(document).on('ready', function() {
     handler = Gmaps.build('Google');
     handler.buildMap({ internal: { id: 'map' } }, function(){
       markers = handler.addMarkers(<%= raw @markers.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
     });
   })
 <% end %>
<% end %>