config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users do
    resources :accomodations do #, except: [:show] do
      resources :photos, only: [:new, :create]
      resources :bookings, only: [:edit, :index]
    end
  end

  resources :bookings, only: [:edit, :update, :destroy]

  resources :accomodations, only: [:index, :show, :new, :update, :edit] do
    resources :bookings, only: [:new, :index, :create]
    resources :photos, only: [:new, :create]
    resources :flat_reviews, only: [:new, :create]
  end

  resources :photos, only: [:destroy] # DO NOT CHANGE THIS ROUTE

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accomodations, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :flat_reviews

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @user_owned_accomodations = @user.accomodations # nesting accomodations OWNED by the user
    @new_user_accomodation = Accomodation.new # adding possibility to user to add
    # a new accomodation directly from its profile page
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :description, :picture)
  end

  def set_user
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_create_new_accomodation_form.html.erb
<%= simple_form_for [@user, @new_user_accomodation] do |f| %>
  <%= f.error_notification %>
  <%= f.input :address %>
  <%= f.input :street_number, input_html: { id: 'street_number' }, as: :hidden %>
  <%= f.input :route, input_html: { id: 'route' }, as: :hidden %>
  <%= f.input :locality, input_html: { id: 'locality' }, as: :hidden %>
  <%= f.input :country, input_html: { id: 'country' }, as: :hidden %>
  <%= f.input :description %>
  <%= f.input :accomodates %>
  <%= f.input :night_rate %>
  <%= f.button :submit %>
<% end %>

app/views/users/_show_owned_accomodations.html.erb
<% @user_owned_accomodations.each do | accomodation | %>
  <div class="row my-accomodation-box text-left">
    <div class="col-xs-12 col-sm-6">
      <% if accomodation.photos.present? %>
      <%= image_tag(accomodation.photos.sample.picture.url(:medium), height: '180', width: '250') %>
      <% else %>
      <%= image_tag ("default.jpg"), height: '180', width: '250' %>
      <% end %>

    </div>
    <div class="col-xs-12 col-sm-6">
      <p><%= link_to accomodation.description, user_accomodation_path(@user, accomodation) %></p>
      <p><span>€ </span><%= accomodation.night_rate %></p>
      <p><%=  link_to "Update this accomodation", edit_user_accomodation_path(@user, accomodation), class: "btn btn-default btn-sm" %></p>
      <p><%= link_to "Delete this accomodation", user_accomodation_path(@user, accomodation), method: :delete, class: "btn btn-default btn-sm" %></p>
    </div>
  </div>
  <div class="row my-accomodation-box text-left">
    <div class="col-xs-12 col-sm-12">
      <h5>Current bookings on this accomodation</h5>
      <% accomodation.bookings.each do |booking| %>
        <div class="row">
          <div class="col-xs-8">
            <p><%= "Booked from #{booking.from.strftime("%F")} to #{booking.to.strftime("%F")} " %></p>
          </div>
          <div class="col-xs-4 text-right">
            <% if booking.reviewed == false %>
              <p><%= link_to "Review", edit_booking_path(booking) %></p>
            <% else %>
              <% if booking.accepted == true %>
                <p><%= "Accepted" %></p>
              <% else %>
                <p><%= "Rejected" %></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_show_personal_data.html.erb
<div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <div id="presentation-box" class="card-block shadowed-box">
    <div class="img-wrapper">

      <% if current_user.picture.present? %>
                <%= image_tag current_user.picture.url(:medium), class: "top-img img-circle" %>
                <% else %>
                <%= image_tag ("beard-man-logo.png"), class: "top-img img-circle" %>
                <% end %>


    </div>
    <div class="main-title-block">
      <h1 class="main-title"><%= "#{@user.first_name}  #{@user.last_name}" %></h1>
      <h4 class="main-subtitle"><%= "#{@user.email}" %></h4>
    </div>
    <div class="desc-wrapper">
      <p><%= "#{@user.description}" %></p>
    </div>
    <div>
      <%= link_to "Edit profile", edit_user_path(@user) %>
    </div>
  </div>
  <div id="keep-in-touch-box" class="card-block shadowed-box">
    <h3>My rating</h3>
    <ul id="social-list" class="unbulleted-list">
      <li>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star"></i>
        <i class="fa fa-star-o"></i>
      </li>
    </ul>
  </div>
</div>

app/views/users/_show_renter_bookings.html.erb
<% @user.bookings.each do | booking | %>
  <div class="row my-booking-box text-left">
    <div class="col-xs-12 col-sm-6">
      <%= image_tag("flat_1.jpg", height: '180', width: '250') %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <p>Which flat? <%= "#{booking.accomodation.description}" %></p>
      <p>Where? <%= "#{booking.accomodation.locality}, #{booking.accomodation.country}" %></p>
      <p>When? <%= "from #{booking.from.strftime("%F")} to #{booking.to.strftime("%F")}" %></p>
      <p>Cost? $
        <%= "#{((booking.to - booking.from)/86400) * booking.accomodation.night_rate }" %>
      </p>
      <p>
        Status?
        <% if booking.reviewed == false %>
          <%= "Pending review" %>
        <% else %>
          <% if booking.accepted == true %>
            <%= "Accepted" %>
          <% else %>
            <%= "Rejected" %>
          <% end %>
        <% end %>
      </p>
      <p>
        <%= link_to 'Cancel this booking', booking_path(booking), method: 'delete', class: "btn btn-default btn-xs"%>
      </p>
    </div>
  </div>
<% end %>

<!-- /86400000 -->

app/views/users/_show_user_reviews.html.erb
<table width="100%">
  <tr>
    <td>
      <%= image_tag "paris.jpg", class: "city-img"%>
    </td>
    <td>
      <h4>Paris</h4>
      <p>Paris is the capital city of France. It is located in France and France is surrounding it. It is populated by French people.</p>
    </td>
  </tr>
  <tr>
    <td>
      <%= image_tag "rio.jpg", class: "city-img"%>
    </td>
    <td>
      <h4>Rio de Janeiro</h4>
      <p>Rio de Janeiro is the former capital city of Brazil. It is located in Brazil and Brazil is surrounding it. It is populated by Brazilian people.</p>
    </td>
  </tr>
  <tr>
    <td>
      <%= image_tag "bruxelles.jpg", class: "city-img"%>
    </td>
    <td>
      <h4>Bruxelles</h4>
      <p>Bruxelles is the capital city of Belgium. It is located in Belgium and Belgium is surrounding it. It is populated by Belgian people.</p>
    </td>
  </tr>
  <tr>
    <td>
      <%= image_tag "roma.jpg", class: "city-img"%>
    </td>
    <td>
      <h4>Roma</h4>
      <p>Roma is the capital city of the Roman Empire. It is located in Italy and Italy is surrounding it. It is populated by Romans.</p>
    </td>
  </tr>
  <tr>
    <td>
      <%= image_tag "marseille.jpg", class: "city-img"%>
    </td>
    <td>
      <h4>Marseille</h4>
      <p>Marseille is the capital city of nothing. It is located in Provence and Provence is surrounding it. It is populated by... nobody knows.</p>
    </td>
  </tr>
</table>

app/views/users/edit.html.erb
<div class="container text-center">
  <div id="myBackLinkRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left">
      <div id="presentation-box" class="card-block shadowed-box centered-text">
        <div class="main-title-block">
          <h1 class="main-title">Update your profile</h1>
        </div>
        <%= simple_form_for @user do |f| %>
          <%= f.file_field :picture %>
          <%= image_tag @user.picture.url(:medium), class:"top-img img-circle" %>
          <%= f.input :first_name %>
          <%= f.input :last_name %>
          <%= f.input :email %>
          <%= f.input :description %>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- TEMPORARY USER INDEX -->
<!-- TO BE DELETED WHEN AUTHENTICATION SYSTEM WILL BE READY -->
<div class="container text-center">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div id="presentation-box" class="card-block shadowed-box">
        <h3>Temporary Users List</h3>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% @users.each do | user | %>
      <div id="presentation-box" class="card-block shadowed-box text-left">
        <div class="row my-accomodation-box text-left">
          <div class="col-xs-12 col-sm-3">
            <div class="img-wrapper">
              <%= image_tag( user.picture, class: "top-img img-circle")%>
            </div>
          </div>
          <div class="col-xs-12 col-sm-8 col-sm-offset-1">
            <h1 class="main-title"><%= "#{user.first_name} #{user.last_name}" %></h1>
            <h4 class="main-subtitle"><%= user.email %></h4>
            <p><%= link_to "See profile", user_path(user) %></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <div id="myBackLinkRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-1 text-left">
      <%= link_to "Back to Accomodation List", accomodations_path %>
    </div>
  </div>
  <div id="myHeaderRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        My profile
      </h1>
      <p>
        Welcome
      </p>
    </div>
  </div>
  <div id="myPersonalDataRow" class="row">
    <%= render "show_personal_data" %>
  </div>
  <div id="myBookingsRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div id="myBookings">
        <div id="bookingsBox" class="card-block shadowed-box">
          <h3>My Bookings</h3>
          <%= render "show_renter_bookings" %>
        </div>
      </div>
    </div>
  </div>
  <div id="myOwnedAccomodationsRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div id="ownedAccomodationsBox" class="card-block shadowed-box">
        <h3>My accomodations</h3>
         <%= render "show_owned_accomodations" %>
      </div>
    </div>
  </div>
  <div id="myAddAccomodationRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div id="addNewAccomodationBox" class="card-block shadowed-box">
        <h3>Add a new accomodation</h3>
        <%= render "create_new_accomodation_form" %>
      </div>
    </div>
  </div>
  <div id="myReviewsRow" class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div id="userReviews">
        <div id="favorites-cities-box" class="card-block shadowed-box">
          <h3>My reviews</h3>
          <%= render "show_user_reviews" %>
        </div>
      </div>
    </div>
  </div>
</div>