config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users do
    resources :accomodations do #, except: [:show] do
      resources :photos, only: [:new, :create]
      resources :bookings, only: [:edit, :index]
    end
  end

  resources :bookings, only: [:edit, :update, :destroy]

  resources :accomodations, only: [:index, :show, :new, :update, :edit] do
    resources :bookings, only: [:new, :index, :create]
    resources :photos, only: [:new, :create]
    resources :flat_reviews, only: [:new, :create]
  end

  resources :photos, only: [:destroy] # DO NOT CHANGE THIS ROUTE

  root 'welcome#index'

end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  has_many :photos
  belongs_to :user
  # belongs_to :owner, source: :user
  has_many :bookings, dependent: :destroy
  has_many :renters, through: :bookings, source: :user
  has_many :flat_reviews, dependent: :destroy
  # belongs_to :user, class_name: "Owner", foreign_key: "owner_id"
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :description,
              presence: true
  validates :user_id,
              presence: true,
              numericality: { only_integer: true }
  validates :accomodates,
              presence: true,
              numericality: { only_integer: true }
  validates :night_rate,
              presence: true,
              numericality: { only_integer: true }
  validates :address,
              presence: true

  def self.search(query)
    #where(:locality, query) #-> This would return an exact match of the query
    where("locality like ?", "%#{query}%")
  end
end

# accomodates -> integer
# description -> text
# night_rate -> integer
# address -> string
# owner_id -> integer
# latitude -> float
# longitude -> float

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :accomodation
  belongs_to :user
  validates :from, presence: :true, numericality: true
  validates :to, presence: :true, numericality: true
end

app/models/flat_review.rb
class FlatReview < ActiveRecord::Base
  belongs_to :accomodation
  belongs_to :user
  validates :content,
              presence: true
  validates :rating,
              presence: true,
              numericality: { only_integer: true }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :accomodation

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :accomodations, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :flat_reviews

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_user, only: [:create, :update, :destroy]
  before_action :set_accomodation, only: [:create]
  before_action :set_booking, only: [:edit, :update]

  def create
    @booking = @accomodation.bookings.build(renter_booking_params)
    @booking.user_id = @user.id
    @booking.accepted = false
    @booking.reviewed = false
    @booking.save
    redirect_to accomodation_path(@accomodation)
  end

  def new
  end

  def edit
  end

  def update
    if update_params["accepted"] == "1" # TO DO: DISCUSS WITH SIMON
      @booking.update({from: @booking.from, to: @booking.to, accepted: true, reviewed: true})
      flash[:notice] = "The booking request has been accepted!"
    else
      @booking.update({from: @booking.from, to: @booking.to, accepted: false, reviewed: true})
      flash[:notice] = "The booking request has been rejected!"
    end
    redirect_to user_path(@user)
  end

  def destroy
    if @booking = Booking.find(params[:id])
      if @user.id == @booking.user.id
        @booking.destroy
        flash[:notice] = "The booking request has been deleted!"
        redirect_to user_path(@user)
      else
        flash[:alert] = "You do not have the right to reject this booking request!"
        redirect_to user_path(@user)
      end
    else
      flash[:alert] = "The booking that you are trying to delete has already been delete. Refresh your navigator!"
      redirect_to user_path(@user)
    end
  end

  def index
  end

  def show
  end

  private

  def update_params
    params.require(:booking).permit(:accepted)
  end

  def renter_booking_params
    params.require(:booking).permit(:from, :to)
  end

  def set_user
    @user = current_user
    # @user = User.find(params[:user_id])
  end

  def set_accomodation
    @accomodation = Accomodation.find(params[:accomodation_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/flat_reviews_controller.rb
class FlatReviewsController < ApplicationController
  before_action :set_user, only: [ :create ]
  before_action :set_accomodation, only: [ :create ]

  def create
    @flat_review = @accomodation.flat_reviews.build(flat_reviews_params)
    @flat_review.user_id = @user.id
    @flat_review.save
    redirect_to accomodation_path(@accomodation)
  end

  private

  def flat_reviews_params
    params.require(:flat_review).permit(:rating, :content)
  end

  def set_user
    @user = current_user
  end

  def set_accomodation
    @accomodation = Accomodation.find(params[:accomodation_id])
  end
end

# accomodates -> integer
# description -> text
# night_rate -> integer
# address -> string
# owner_id -> integer
# latitude -> float
# longitude -> float

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user, only: [:destroy]
  # before_action :set_accomodation, only: [:destroy]

  def new
  end

  def create
    @accomodation = Accomodation.find(params[:accomodation_id])
    @photo = @accomodation.photos.build(photo_params)
    @photo.save
    redirect_to @accomodation
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to user_path(@user)
    # redirect_to @accomodation
  end

  private

  def photo_params
    params.require(:photo).permit(:picture)
  end

  def set_user
    @user = current_user
  end

  def set_accomodation
    @accomodation = Accomodation.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @user_owned_accomodations = @user.accomodations # nesting accomodations OWNED by the user
    @new_user_accomodation = Accomodation.new # adding possibility to user to add
    # a new accomodation directly from its profile page
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :description, :picture)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user! # SKIPPING LOGIN FOR SOME PAGES

  def index
  end

end

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flat_reviews_helper.rb
module FlatReviewsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>HairBnb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Cookie" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render "shared/navbar" %>

  <%= render 'shared/notices' %>
  <%= render 'shared/alerts' %>

  <%= yield %>

  <%= render "shared/footer" %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyDiLbha2ADV-c4IjSgjFFCj01FcwrOHteI" %>

  <%= yield(:after_js) %>
</body>
</html>

app/views/shared/_accomodation_form.html.erb
<%= simple_form_for(@accomodation, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :address  %>
  <%= f.input :description %>
  <%= f.input :accomodates %>
  <%= f.input :night_rate %>
  <%= f.button :submit %>
<% end %>
<p><%= link_to "(or go back to my profile)", user_path(current_user) %></p>

app/views/shared/_accomodation_gallery.html.erb
<% @accomodation.photos.each do |photo| %>
<p>
  <%= image_tag photo.picture.url(:medium), class:"img-thumbnail", width:"300px" %>
  <%= link_to('delete', photo_path(photo), method: :delete) %>
</p>
<% end %>

app/views/shared/_alerts.html.erb
<% if alert %>
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_booking_confirmation_form.html.erb
<p><%= "#{@booking.accomodation.description}" %></p>
<p><%= "Booking request from #{@booking.from.strftime("%F")} to #{@booking.to.strftime("%F")}" %></p>
<p>
  <%= "Confirmation status:"%>
  <% if @booking.accepted == false %>
    <%= "pending" %>
    <%= simple_form_for(@booking, html: { multipart: true }) do |f| %>
      <%= f.error_notification %>
      <%= f.input :accepted, as: :boolean %>
      <%= f.button :submit %>
    <% end %>
  <% else %>
    <%= "accepted" %>
  <% end %>
</p>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">

  <div class="footer-left">

    <h3>Hair<span>BnB</span></h3>

    <p class="footer-links">
      <a href="#">Home</a>
      ·
      <a href="#">Pricing</a>
      ·
      <a href="#">About</a>
      ·
      <a href="#">Faq</a>
      ·
      <a href="#">Contact</a>
    </p>

    <p class="footer-company-name">Hairbnb &copy; 2015</p>
  </div>

  <div class="footer-center">

    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>21 Revolution Street</span> Paris, France</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>+1 555 123456</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:support@hairbnb.com">support@hairbnb.com</a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>About the company</span>
      We rule
    </p>

    <div class="footer-icons">

      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>

    </div>

  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to( root_path, class: "navbar-brand") do %>
        <%= image_tag("beard-man-logo.png") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
               <% if current_user.picture.present? %>
                <%= image_tag current_user.picture.url(:medium), class: "img-avatar" %>
                <% else %>
                <%= image_tag ("beard-man-logo.png"), class: "img-avatar" %>
                <% end %>
              Profile <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "View profile", user_path(current_user) %>
              </li>
              <li>
                <%= link_to "Edit profile", edit_user_path(current_user) %>
              </li>
              <!--<li>
                <%= link_to "Add an accomodation", new_accomodation_path %>-->
              </li>
              <li>
                <%= link_to "View all accomodations", accomodations_path %>
              </li>
              <li>
                <%= link_to 'Sign out', destroy_user_session_path, method: 'delete'%>
              </li>
            </ul>
          </li>
        <% else %>
          <!-- UNLOGGED NAVIGATION BAR FEATURES -->
          <li>
            <%= link_to 'Sign up', new_user_registration_path %>
          </li>
          <li>
          <%= link_to 'Sign in', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_photo_form.html.erb
<%= simple_form_for([@accomodation, Photo.new], html: { multipart: true }) do |f| %>
    <%= f.error_notification %>
    <%= f.input :picture %>
    <%= f.input :picture %>
    <%= f.input :picture %>
    <%= f.input :picture %>
    <%= f.button :submit %>
<% end %>

app/views/shared/optionalfoot.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright &copy; Hair-BnB 2015</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li><a href="http://twitter.com/hairbnb"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="http://facebook.com/hairbnb"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="https://www.linkedin.com/company/hairbnb"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li><a href="#">Privacy Policy</a>
                    </li>
                    <li><a href="#">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>